export const products = [
    {
        id: 1,
        name: 'Thịt heo xào hành tây',
        price: 230000,
        star: 4.5,
        starCount: 125,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Thịt heo', amount: '300g' },
            { name: 'Hành tây', amount: '150g' },
            { name: 'Tỏi', amount: '20g' },
            { name: 'Gia vị', amount: 'Vừa đủ' },
            { name: 'Dầu ăn', amount: '30ml' },
        ],
        nutrition: [
            { name: 'Calo', amount: '450kcal' },
            { name: 'Protein', amount: '28g' },
            { name: 'Carbohydrate', amount: '15g' },
            { name: 'Chất béo', amount: '32g' },
            { name: 'Cholesterol', amount: '85mg' },
        ],
        allergy: [{ name: 'Không phù hợp cho người dị ứng thịt heo' }, { name: 'Có thể chứa dấu vết của đậu nành' }],
    },
    {
        id: 2,
        name: 'Gà nướng lá chanh',
        price: 250000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Đùi gà', amount: '400g' },
            { name: 'Lá chanh', amount: '10 lá' },
            { name: 'Sả', amount: '3 cây' },
            { name: 'Ớt', amount: '2 quả' },
            { name: 'Gia vị ướp', amount: 'Vừa đủ' },
        ],
        nutrition: [
            { name: 'Calo', amount: '520kcal' },
            { name: 'Protein', amount: '35g' },
            { name: 'Carbohydrate', amount: '12g' },
            { name: 'Chất béo', amount: '38g' },
            { name: 'Cholesterol', amount: '120mg' },
        ],
        allergy: [{ name: 'Không phù hợp cho người dị ứng thịt gà' }],
    },
    {
        id: 3,
        name: 'Tôm sú hấp bia',
        price: 280000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Tôm sú', amount: '500g' },
            { name: 'Bia', amount: '200ml' },
            { name: 'Gừng', amount: '30g' },
            { name: 'Hành lá', amount: '20g' },
            { name: 'Gia vị', amount: 'Vừa đủ' },
        ],
        nutrition: [
            { name: 'Calo', amount: '320kcal' },
            { name: 'Protein', amount: '32g' },
            { name: 'Carbohydrate', amount: '8g' },
            { name: 'Chất béo', amount: '18g' },
            { name: 'Cholesterol', amount: '180mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng hải sản' },
            { name: 'Có chứa gluten từ bia' },
            { name: 'Có chứa đồ uống có cồn' },
        ],
    },
    {
        id: 4,
        name: 'Bò lúc lắc khoai tây',
        price: 270000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Thịt bò', amount: '350g' },
            { name: 'Khoai tây', amount: '200g' },
            { name: 'Ớt chuông', amount: '100g' },
            { name: 'Hành tây', amount: '80g' },
            { name: 'Gia vị ướp', amount: 'Vừa đủ' },
        ],
        nutrition: [
            { name: 'Calo', amount: '480kcal' },
            { name: 'Protein', amount: '38g' },
            { name: 'Carbohydrate', amount: '25g' },
            { name: 'Chất béo', amount: '28g' },
            { name: 'Cholesterol', amount: '95mg' },
        ],
        allergy: [{ name: 'Không phù hợp cho người dị ứng thịt bò' }, { name: 'Có thể chứa dấu vết của đậu nành' }],
    },
    {
        id: 5,
        name: 'Mực chiên giòn',
        price: 220000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Mực tươi', amount: '400g' },
            { name: 'Bột chiên giòn', amount: '150g' },
            { name: 'Trứng gà', amount: '2 quả' },
            { name: 'Chanh', amount: '1 quả' },
            { name: 'Gia vị ướp', amount: 'Vừa đủ' },
        ],
        nutrition: [
            { name: 'Calo', amount: '380kcal' },
            { name: 'Protein', amount: '25g' },
            { name: 'Carbohydrate', amount: '28g' },
            { name: 'Chất béo', amount: '22g' },
            { name: 'Cholesterol', amount: '120mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng hải sản' },
            { name: 'Chứa trứng' },
            { name: 'Có thể chứa gluten từ bột chiên' },
        ],
    },
    {
        id: 6,
        name: 'Lẩu thái hải sản',
        price: 350000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Nước lẩu thái', amount: '1.5 lít' },
            { name: 'Tôm sú', amount: '300g' },
            { name: 'Mực', amount: '200g' },
            { name: 'Nấm các loại', amount: '150g' },
            { name: 'Rau thơm', amount: '100g' },
            { name: 'Mì', amount: '200g' },
        ],
        nutrition: [
            { name: 'Calo', amount: '580kcal' },
            { name: 'Protein', amount: '42g' },
            { name: 'Carbohydrate', amount: '35g' },
            { name: 'Chất béo', amount: '30g' },
            { name: 'Cholesterol', amount: '210mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng hải sản' },
            { name: 'Có thể chứa gluten từ mì' },
            { name: 'Có thể chứa đậu nành' },
            { name: 'Cay nồng' },
        ],
    },
    {
        id: 7,
        name: 'Sườn nướng mật ong',
        price: 260000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Sườn heo', amount: '500g' },
            { name: 'Mật ong', amount: '50ml' },
            { name: 'Tỏi', amount: '30g' },
            { name: 'Gia vị ướp', amount: 'Vừa đủ' },
            { name: 'Rau thơm', amount: '50g' },
        ],
        nutrition: [
            { name: 'Calo', amount: '550kcal' },
            { name: 'Protein', amount: '35g' },
            { name: 'Carbohydrate', amount: '18g' },
            { name: 'Chất béo', amount: '40g' },
            { name: 'Cholesterol', amount: '110mg' },
        ],
        allergy: [{ name: 'Không phù hợp cho người dị ứng thịt heo' }, { name: 'Có thể chứa dấu vết của mật ong' }],
    },
    {
        id: 8,
        name: 'Ngao hấp sả',
        price: 180000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Ngao tươi', amount: '600g' },
            { name: 'Sả', amount: '5 cây' },
            { name: 'Gừng', amount: '30g' },
            { name: 'Ớt', amount: '2 quả' },
            { name: 'Rau thơm', amount: '50g' },
        ],
        nutrition: [
            { name: 'Calo', amount: '280kcal' },
            { name: 'Protein', amount: '32g' },
            { name: 'Carbohydrate', amount: '8g' },
            { name: 'Chất béo', amount: '15g' },
            { name: 'Cholesterol', amount: '90mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng hải sản' },
            { name: 'Có thể chứa dấu vết của đậu nành trong nước chấm' },
        ],
    },
    {
        id: 9,
        name: 'Cá chép om dưa',
        price: 300000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Cá chép tươi', amount: '1 con (700g)' },
            { name: 'Dưa chua', amount: '300g' },
            { name: 'Cà chua', amount: '200g' },
            { name: 'Gừng', amount: '30g' },
            { name: 'Hành lá', amount: '50g' },
            { name: 'Gia vị', amount: 'Vừa đủ' },
        ],
        nutrition: [
            { name: 'Calo', amount: '420kcal' },
            { name: 'Protein', amount: '35g' },
            { name: 'Carbohydrate', amount: '15g' },
            { name: 'Chất béo', amount: '25g' },
            { name: 'Cholesterol', amount: '120mg' },
        ],
        allergy: [{ name: 'Không phù hợp cho người dị ứng cá' }, { name: 'Có thể chứa dấu vết của các loại gia vị' }],
    },
    {
        id: 10,
        name: 'Nem rán hải sản',
        price: 200000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Tôm', amount: '150g' },
            { name: 'Cua', amount: '100g' },
            { name: 'Mực', amount: '100g' },
            { name: 'Bánh đa nem', amount: '20 miếng' },
            { name: 'Miến', amount: '50g' },
            { name: 'Nấm mèo', amount: '30g' },
            { name: 'Rau thơm', amount: '50g' },
        ],
        nutrition: [
            { name: 'Calo', amount: '350kcal' },
            { name: 'Protein', amount: '25g' },
            { name: 'Carbohydrate', amount: '30g' },
            { name: 'Chất béo', amount: '18g' },
            { name: 'Cholesterol', amount: '110mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng hải sản' },
            { name: 'Có thể chứa gluten từ bánh đa nem' },
            { name: 'Có thể chứa dấu vết của đậu nành' },
        ],
    },
    {
        id: 11,
        name: 'Ếch xào sả ớt',
        price: 230000,
        star: 4.5,
        starCount: 12,
        time: '15-20',
        description: 'Thịt heo thái mỏng, xào cùng hành tây tươi thơm lừng. Sự kết hợp mặn ngọt hài hòa.',
        image: 'https://storage.quannhautudo.com/data/thumb_400/Data/images/product/2024/06/202406051701344383.webp',
        ingredients: [
            { name: 'Đùi ếch', amount: '500g' },
            { name: 'Sả', amount: '5 cây' },
            { name: 'Ớt', amount: '4 quả' },
            { name: 'Hành tím', amount: '50g' },
            { name: 'Tỏi', amount: '30g' },
            { name: 'Rau thơm', amount: '50g' },
        ],
        nutrition: [
            { name: 'Calo', amount: '320kcal' },
            { name: 'Protein', amount: '30g' },
            { name: 'Carbohydrate', amount: '10g' },
            { name: 'Chất béo', amount: '20g' },
            { name: 'Cholesterol', amount: '85mg' },
        ],
        allergy: [
            { name: 'Không phù hợp cho người dị ứng thịt ếch' },
            { name: 'Có thể chứa dấu vết của các loại gia vị cay' },
        ],
    },
];

export const categories = ['Gợi ý', 'Combo', 'Khai vị', 'Salad', 'Món Chính', 'Tráng Miệng', 'Đồ Uống', 'Lẩu', 'Súp'];

// Các món đang được chọn, chưa đặt
export const currentSelectedItem = [
    {
        id: 1,
        productId: 1,
        name: 'Thịt heo xào hành tây',
        price: 230000,
        quantity: 1,
        note: 'Không hành',
        options: [
            {
                type: 'Thêm thịt',
                items: [{ name: 'Thịt thêm', quantity: 0.5, price: 50000 }],
            },
            {
                type: 'Độ cay',
                items: [{ name: 'Nhẹ' }],
            },
        ],
    },
    {
        id: 2,
        productId: 2,
        name: 'Gà nướng lá chanh',
        price: 250000,
        quantity: 2,
        note: 'Nhiều chanh',
        options: [
            {
                type: 'Món ăn kèm',
                items: [{ name: 'Cơm trắng', quantity: 1, price: 15000 }],
            },
        ],
    },
    {
        id: 3,
        productId: 5,
        name: 'Mực chiên giòn',
        price: 220000,
        quantity: 1,
        note: 'Giòn nhiều',
        options: [
            {
                type: 'Nước chấm',
                items: [{ name: 'Sốt me', quantity: 1, price: 15000 }],
            },
            {
                type: 'Cách chế biến',
                items: [{ name: 'Chiên giòn' }],
            },
            {
                type: 'Độ cay',
                items: [{ name: 'Vừa' }],
            },
        ],
    },
    {
        id: 4,
        productId: 5,
        name: 'Mực chiên giòn',
        price: 220000,
        quantity: 1,
        note: 'Giòn nhiều',
        options: [
            {
                type: 'Nước chấm',
                items: [{ name: 'Sốt me', quantity: 1, price: 15000 }],
            },
            {
                type: 'Cách chế biến',
                items: [{ name: 'Chiên giòn' }],
            },
            {
                type: 'Độ cay',
                items: [{ name: 'Vừa' }],
            },
        ],
    },
];

// Các món đã đặt, có trạng thái
export const alreadyOrdered = [
    {
        id: 101,
        productId: 3,
        name: 'Tôm sú hấp bia',
        price: 280000,
        quantity: 2,
        orderTime: '11:30',
        status: 'pending', // Chờ tiếp nhận
        note: 'Tươi sống',
        options: [
            {
                type: 'Rau',
                items: [{ name: 'Rau thơm', quantity: 1, price: 0 }],
            },
        ],
    },
    {
        id: 102,
        productId: 4,
        name: 'Bò lúc lắc khoai tây',
        price: 270000,
        quantity: 1,
        orderTime: '11:25',
        status: 'processing', // Đang chế biến
        note: 'Bò tái',
        options: [
            {
                type: 'Món ăn kèm',
                items: [{ name: 'Khoai tây thêm', quantity: 1, price: 30000 }],
            },
            {
                type: 'Mức độ chín',
                items: [{ name: 'Tái' }],
            },
            {
                type: 'Độ cay',
                items: [{ name: 'Cay' }],
            },
        ],
    },
    {
        id: 103,
        productId: 6,
        name: 'Lẩu thái hải sản',
        price: 350000,
        quantity: 1,
        orderTime: '11:15',
        status: 'served', // Đã phục vụ
        note: 'Nhiều nấm',
        options: [
            {
                type: 'Mì',
                items: [{ name: 'Mì thêm', quantity: 1, price: 20000 }],
            },
            {
                type: 'Hải sản',
                items: [{ name: 'Hải sản thêm', quantity: 1, price: 100000 }],
            },
            {
                type: 'Rau củ',
                items: [{ name: 'Nấm thêm', quantity: 1, price: 25000 }],
            },
            {
                type: 'Độ cay',
                items: [{ name: 'Siêu cay' }],
            },
        ],
    },
    {
        id: 104,
        productId: 8,
        name: 'Ngao hấp sả',
        price: 180000,
        quantity: 1,
        orderTime: '11:10',
        status: 'cancelled', // Đã hủy
        note: 'Nhiều sả',
        options: [
            {
                type: 'Rau',
                items: [{ name: 'Rau thơm', quantity: 1, price: 0 }],
            },
            {
                type: 'Nước chấm',
                items: [{ name: 'Nước mắm', quantity: 1, price: 0 }],
            },
        ],
    },
];

// export const currentSelectedItem = [];
// export const alreadyOrdered = [];

export const bookingList = [
    {
        id: 1,
        full_name: 'Leia Moodey',
        phone_number: '0947628127',
        people_numbers: 10,
        booking_at: '2025-06-18 14:30:00',
        floor_name: '1',
        area_name: 'A',
        table_name: '1',
        status: 'PENDING_CONFIRMATION',
        products: [
            { pro_code: 1, quantity: 2, price: 10000 },
            { pro_code: 2, quantity: 3, price: 10000 },
        ],
        created_at: '2024-06-01T10:00:00Z',
    },
    {
        id: 2,
        full_name: 'Marie-jeanne Simonnet',
        phone_number: '673-420-9859',
        people_numbers: 4,
        booking_at: '2025-06-18 14:30:00',
        table_name: '2',
        booking_code: 'BBBB44',
        status: 'CONFIRMED',
        area_name: 'A',
        floor_name: 2,
        products: [
            { pro_code: 1, quantity: 2, price: 10000 },
            { pro_code: 2, quantity: 3, price: 10000 },
        ],
        created_at: '2024-06-01T10:00:00Z',
        created_booking_code_at: '2024-06-01T11:00:00Z',
    },
    {
        id: 3,
        full_name: 'Graig McCadden',
        phone_number: '902-952-4311',
        people_numbers: 9,
        booking_at: '2025-06-18 14:30:00',
        status: 'PENDING_CONFIRMATION',
        area_name: 'B',
        floor_name: 3,
        products: [
            { pro_code: 1, quantity: 2, price: 10000 },
            { pro_code: 2, quantity: 3, price: 10000 },
        ],
        created_at: '2024-06-01T10:00:00Z',
    },
    {
        id: 4,
        full_name: 'Adler Massinger',
        phone_number: '912-406-2479',
        people_numbers: 7,
        booking_at: '18-06-2025 14:30:00',
        table_name: '10',
        booking_code: '1123C',
        status: 'LATE',
        area_name: 'B',
        floor_name: 4,
        products: [
            { pro_code: 1, quantity: 2, price: 10000 },
            { pro_code: 2, quantity: 3, price: 10000 },
        ],
        created_at: '2024-06-01T10:00:00Z',
        created_booking_code_at: '2024-06-01T11:00:00Z',
        completed_at: '2025-06-18 14:30:00',
    },
    {
        id: 5,
        full_name: 'Neal Obert',
        phone_number: '736-284-0427',
        people_numbers: 8,
        booking_at: '2025-06-18 14:30:00',
        table_name: '14',
        booking_code: 'DDDF2',
        status: 'CANCELLED',
        area_name: '3',
        floor_name: 5,
        products: [
            { pro_code: 1, quantity: 2, price: 10000 },
            { pro_code: 2, quantity: 3, price: 10000 },
        ],
        created_at: '2024-06-01T10:00:00Z',
        note: 'Khách hủy do bận việc đột xuất',
        cancel_reason: 'Bận việc đột xuất',
        created_booking_code_at: '2024-06-01T11:00:00Z',
    },
];

export const tableList = [
    { flo_code: 1, area_code: 'A', tab_code: '1', tab_name: '1', status: 'EMPTY', capacity: 4 },
    { flo_code: 1, area_code: 'A', tab_code: '2', tab_name: '2', status: 'OCCUPIED', capacity: 4 },
    { flo_code: 1, area_code: 'A', tab_code: '3', tab_name: '3', status: 'RESERVED', capacity: 4 },
    { flo_code: 1, area_code: 'A', tab_code: '4', tab_name: '4', status: 'CLEANING', capacity: 4 },
    { flo_code: 1, area_code: 'A', tab_code: '5', tab_name: '5', status: 'MAINTENANCE', capacity: 4 },
    { flo_code: 2, area_code: 'A', tab_code: '6', tab_name: '6', status: 'EMPTY', capacity: 4 },
    {
        flo_code: 2,
        area_code: 'A',
        tab_code: '7',
        tab_name: '7',
        status: 'RESERVED',
        completed_at: '2025-06-19T14:15:00',
        capacity: 4,
    },
    {
        flo_code: 2,
        area_code: 'A',
        tab_code: '8',
        tab_name: '8',
        status: 'RESERVED',
        completed_at: '2025-06-19T12:30:00',
        capacity: 4,
    },
    { flo_code: 2, area_code: 'A', tab_code: '9', tab_name: '9', status: 'EMPTY', capacity: 4 },
];

export const floorList = [
    { flo_code: 1, flo_name: 1 },
    { flo_code: 2, flo_name: 2 },
    { flo_code: 3, flo_name: 3 },
];

export const areaList = [
    { area_code: 1, area_name: 'A' },
    { area_code: 2, area_name: 'B' },
    { area_code: 3, area_name: 'C' },
];
